### ISSUE TITLE
Depends on azure-storage only

### ISSUE THREAD

**Issue by lijunle** [jpoon/winston-azuretable#1]
The package [azure](https://www.npmjs.com/package/azure) is huge, please use the single package [azure-storage](https://www.npmjs.com/package/azure-storage).

Besides, the azure-storage support `AZURE_STORAGE_CONNECTION_STRING` environment variable to authenticate.

**Comment by jpoon** [comment]
@lijunle good point! I'll use azure-storage instead. Will submit update in a bit.

**Comment by jpoon** [comment]
Just pushed a new npm module: https://www.npmjs.com/package/winston-azuretable.

Let me know if you run into any further issues.
