### ISSUE TITLE
'_' is appended to each metadata property name

### ISSUE THREAD

**Issue by mhh** [jpoon/winston-azuretable#3]
Hi,

I just started using winston-azuretable (thanks for making it!) and noticed that it's appending a `_` character to each property name in the metadata I provide when logging a message.  Looks like this happens at https://github.com/jpoon/winston-azuretable/blob/e0beb6d/lib/winston-azuretable.js#L101, but it's not clear to me why it's done.  Could you provide a little context?

**Comment by jpoon** [comment]
Hey @mhh. The underscore is appended as a poor-man's fix to prevent collisions with the existing data columns (e.g. hostname, pid, level, msg, createdDateTime).

**Comment by jpoon** [comment]
Let me know if that makes sense.
