### ISSUE TITLE
Not working with winstone 3.0.0-rc1

### ISSUE THREAD

**Issue by nitin7dc** [jpoon/winston-azuretable#6]

**Comment by jpoon** [comment]
What doesn't work? What are you trying to do? What errors do you see?

**Comment by manikmanshu** [comment]
Breaking change coming from winston 3.0.0rc in winston transport.
Log function receives **info** object instead of level and message as params.

Created [pull request](https://github.com/jpoon/winston-azuretable/pull/7) with fix

**Comment by nitin7dc** [comment]
@manikmanshu has created a pull request with details and the fix. Thanks
